// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUL0ArgOSq2xddAfwgrVf-tLIymK-sv6Y',
    appId: '1:151669483238:web:db640862591a4d97b8fd27',
    messagingSenderId: '151669483238',
    projectId: 'levant-sale',
    authDomain: 'levant-sale.firebaseapp.com',
    storageBucket: 'levant-sale.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUL0ArgOSq2xddAfwgrVf-tLIymK-sv6Y',
    appId: '1:151669483238:android:db640862591a4d97b8fd27',
    messagingSenderId: '151669483238',
    projectId: 'levant-sale',
    storageBucket: 'levant-sale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUL0ArgOSq2xddAfwgrVf-tLIymK-sv6Y',
    appId: '1:151669483238:ios:db640862591a4d97b8fd27',
    messagingSenderId: '151669483238',
    projectId: 'levant-sale',
    storageBucket: 'levant-sale.firebasestorage.app',
    iosBundleId: 'com.example.leventsale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUL0ArgOSq2xddAfwgrVf-tLIymK-sv6Y',
    appId: '1:151669483238:macos:db640862591a4d97b8fd27',
    messagingSenderId: '151669483238',
    projectId: 'levant-sale',
    storageBucket: 'levant-sale.firebasestorage.app',
    iosBundleId: 'com.example.leventsale',
  );
}
